### ISSUE TITLE
Parsing phpBB BBCode

### ISSUE THREAD

**Issue by enniob** [DasRed/js-bbcode-parser#1]
Is it possible to parse phpBB code that has the following format

[quote:5d5097a40c=\"userName\"] some text [/quote:5d5097a40c]

**Comment by DasRed** [comment]
Yes. That is possible. You can create your own instance with your own set of bbcode  definitions or add your own bbcode to the default parser. 

With the default parser you can use the add function. First parameter is the regex object and the second parameter is the replacement.

**Comment by enniob** [comment]
Thanks for the information. I was able to get it working.

**Comment by narendra087** [comment]
> Thanks for the information. I was able to get it working.

can you show me how you do it for that [quote] format? thank you
