### ISSUE TITLE
Can't create my own BBCodes (create is not a function)

### ISSUE THREAD

**Issue by narendra087** [DasRed/js-bbcode-parser#14]
Hi.
i'm using vue and want to create my own BBCodes for [quote=name;date;id]content[/quote]
but when i try to create parser using the example
`const parser = bbCodeParser.create({
    '\\[br\\]': '<br>'
});`
it get error in console

> "TypeError: js_bbcode_parser__WEBPACK_IMPORTED_MODULE_5__.default.create is not a function"

anyone can help me? thank you

**Comment by DasRed** [comment]
The documentation contains a old way to create an own instance. I fixed that and provide a better example, how to create your own BBCode Parser
