### ISSUE TITLE
Give users a note on security issues (XSS)

### ISSUE THREAD

**Issue by Ari24-cb24** [DasRed/js-bbcode-parser#16]
js-bbcode-parser does not purify the user input for xss so it might be a good idea to give the person using the library a short note (e.g include it in the README)

Another idea would be to implement such checks into the library

**Comment by Ari24-cb24** [comment]
Might also mention the library `DomPurify`, its easy to import and should be secure enough

**Comment by DasRed** [comment]
added this information to the README in version v5.0.3

thx. for your hint :)
