### ISSUE TITLE
Headlines become links linking nowhere

### ISSUE THREAD

**Issue by Alacho2** [DasRed/js-bbcode-parser#5]
I really like this parser. It does exactly what I want it to, except that headlines become links. I see that this is done intentionally in the code, but may I ask why?

**Comment by DasRed** [comment]
Hey @Alacho2,

thank you for your feedback. I will take a closer look the next days.

**Comment by DasRed** [comment]
Hey @Alacho2 

I don't know anymore, why i did this. And yes, it makes currently no sense. I have fixed it and have created a new version (v3.0.1).

BTW: You can create your own instance of the BBCode parse with your own rules.
